# Generated by Django 2.1.2 on 2018-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=90)),
                ('text_field1', models.CharField(blank=True, max_length=100, null=True)),
                ('text_field2', models.CharField(blank=True, max_length=100, null=True)),
                ('text_field3', models.CharField(blank=True, choices=[('obj1', 'obj1'), ('obj2', 'obj2'), ('obj3', 'obj3')], max_length=100, null=True)),
                ('text_field4', models.TextField(blank=True, choices=[('obj1', 'obj1'), ('obj2', 'obj2'), ('obj3', 'obj3')], max_length=2000, null=True)),
                ('bool_field', models.BooleanField(default=False)),
                ('date_field1', models.DateField(auto_now=True)),
                ('date_field2', models.DateField(auto_now_add=True)),
                ('datetime_field1', models.DateTimeField(auto_now=True)),
                ('datetime_field2', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
